---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: cosmic-hypr
description: This is my personal OS image based on ublue main with cosmic and hyprland alongside.

base-image: ghcr.io/ublue-os/base-main
image-version: latest # latest is also supported if you want new updates ASAP

modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

# Default changes
  - type: dnf
    repos:
      copr:
      - atim/starship

    install:
      packages:
        - ptyxis
        - gnupg2-scdaemon
        - emacs
        - maildir-utils
        - starship
        - zsh
        - direnv
        - lsd
        - bat
    remove:
      packages:
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

# Load
  - from-file: flathub-packages.yml
  - from-file: cosmic-flatpak-repo.yml
  - from-file: cosmic-packages.yml
# Will remove once cosmic have night light
  - from-file: hyprland-packages.yml

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

